[build]
  command = "npm ci && npm run build"
  # Do NOT set `publish` here for Next.js Runtime v5; plugin handles it.

# Remove the old v4 plugin block from netlify.toml.
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
