[build]
  command = "npm ci && npm run build"
  publish = "dist"   # or ".next", "build", etc. set this to your actual output

[build.environment]
  NODE_VERSION = "20.16.0"
  NPM_FLAGS = "--no-audit --no-fund"