# netlify.toml
[build]
  command = "next build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]                       # SPA routing → always serve index.html
  from = "/*"
  to = "/index.html"
  status = 200
